#!/bin/bash
# gen_const.sh — Generate lib/Nacre/Const.pm from kernel headers.
#
# Usage:
#   scripts/gen_const.sh              # native only (single-arch)
#   scripts/gen_const.sh --cross      # native + aarch64 cross-compile
#   scripts/gen_const.sh --check      # verify Const.pm matches (for CI)
#
# Requirements:
#   - gcc (or cc)
#   --cross additionally needs: gcc-aarch64-linux-gnu, libc6-dev:arm64, qemu-user-static

set -euo pipefail
cd "$(dirname "$0")/.."

SRC=scripts/gen_const.c
OUT=lib/Nacre/Const.pm
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

mode=generate
cross=false
for arg in "$@"; do
    case "$arg" in
        --cross) cross=true ;;
        --check) mode=check ;;
    esac
done

# ── Compile and run ─────────────────────────────────────────────────
echo "Compiling for x86_64..." >&2
cc -Wall -Wextra -o "$TMPDIR/gen_x86" "$SRC"
"$TMPDIR/gen_x86" > "$TMPDIR/x86_64.txt"

if $cross; then
    echo "Cross-compiling for aarch64..." >&2
    aarch64-linux-gnu-gcc -Wall -Wextra -static -o "$TMPDIR/gen_arm" "$SRC"
    qemu-aarch64 "$TMPDIR/gen_arm" > "$TMPDIR/aarch64.txt"
else
    echo "Skipping aarch64 (use --cross to enable)." >&2
    echo "Using existing aarch64 values from $OUT." >&2
fi

# ── Parse output into shell variables ───────────────────────────────
parse_const() {
    local file=$1 prefix=$2
    while IFS='=' read -r key val; do
        # Normalise __NR_foo -> SYS_foo
        key=${key/#__NR_/SYS_}
        eval "${prefix}_${key}=\$val"
    done < "$file"
}

parse_const "$TMPDIR/x86_64.txt" X86

if $cross; then
    parse_const "$TMPDIR/aarch64.txt" ARM
else
    # Extract aarch64 SYS_* from the ARM_CONST block (second 'use constant' in a BEGIN)
    awk '/^package Nacre::Const; use constant \{/{n++} n==2{print} /^\}; 1/{if(n==2) exit}' "$OUT" \
        | grep -oP 'SYS_\w+\s*=>\s*-?\d+' \
        | sed 's/ *=> */=/' > "$TMPDIR/arm_existing.txt"
    if [ -s "$TMPDIR/arm_existing.txt" ]; then
        parse_const "$TMPDIR/arm_existing.txt" ARM
    fi
fi

# ── Helper: look up a constant value ────────────────────────────────
v() {
    local prefix=$1 key=$2
    local varname="${prefix}_${key}"
    echo "${!varname}"
}

# ── Collect SYS_* names (from x86 output, they're the same set) ────
sys_names=()
while IFS='=' read -r key _; do
    key=${key/#__NR_/SYS_}
    [[ $key == SYS_* ]] && sys_names+=("$key")
done < "$TMPDIR/x86_64.txt"

# ── Collect non-SYS constants (arch-independent, from x86 output) ──
declare -A CONST
while IFS='=' read -r key val; do
    key=${key/#__NR_/SYS_}
    [[ $key != SYS_* ]] && CONST[$key]=$val
done < "$TMPDIR/x86_64.txt"

# ── Generate Const.pm ───────────────────────────────────────────────
gen() {
cat <<'HEADER'
package Nacre::Const;
use v5.38;
use Exporter 'import';

# ═══════════════════════════════════════════════════════════════════════
# THIS FILE IS GENERATED by scripts/gen_const.sh — do not edit manually.
# ═══════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════
# Fcntl extras (may not be available on all systems)
# ═══════════════════════════════════════════════════════════════════════
HEADER
printf 'use constant O_CLOEXEC => %s;\n' "${CONST[O_CLOEXEC]}"
printf 'use constant O_PATH => %s;\n' "${CONST[O_PATH]}"

cat <<'SYSCALL_HDR'

# ═══════════════════════════════════════════════════════════════════════
# Syscall numbers (architecture-dependent)
# ═══════════════════════════════════════════════════════════════════════
BEGIN {
    require Config;
    my $a = $Config::Config{archname} // '';    ## no critic (ProhibitPackageVars)
    my $x86 = ($a =~ /x86_64|amd64/i) ? 1 : 0;

    if ($x86) {
        eval <<'X86_CONST' or die $@;    ## no critic (ErrorHandling::RequireCarping)
package Nacre::Const; use constant {
SYSCALL_HDR

# x86_64 syscall table
max_len=0
for name in "${sys_names[@]}"; do
    (( ${#name} > max_len )) && max_len=${#name}
done
for name in "${sys_names[@]}"; do
    printf '    %-*s => %s,\n' "$max_len" "$name" "$(v X86 "$name")"
done

cat <<'MID1'
}; 1
X86_CONST
    } else {
        eval <<'ARM_CONST' or die $@;    ## no critic (ErrorHandling::RequireCarping)
package Nacre::Const; use constant {
MID1

# aarch64 syscall table
for name in "${sys_names[@]}"; do
    if $cross; then
        val=$(v ARM "$name")
    else
        # Fall back to the variable we extracted
        varname="ARM_${name}"
        val="${!varname:--1}"
    fi
    printf '    %-*s => %s,\n' "$max_len" "$name" "$val"
done

cat <<'MID2'
}; 1
ARM_CONST
    }
}
MID2

# Architecture-independent constant sections
emit_section() {
    local title=$1
    shift
    printf '\n# %s\n# %s\n# %s\n' \
        "═══════════════════════════════════════════════════════════════════════" \
        "$title" \
        "═══════════════════════════════════════════════════════════════════════"
    echo 'use constant {'
    for name in "$@"; do
        printf '    %s => %s,\n' "$name" "${CONST[$name]}"
    done
    echo '};'
}

emit_section "Clone / Namespace flags" \
    CLONE_NEWNS CLONE_NEWUTS CLONE_NEWIPC CLONE_NEWUSER CLONE_NEWPID \
    CLONE_NEWNET CLONE_NEWCGROUP CLONE_NEWTIME SIGCHLD

emit_section "Mount flags" \
    MS_RDONLY MS_NOSUID MS_NODEV MS_NOEXEC MS_REMOUNT \
    MS_NOATIME MS_NODIRATIME MS_BIND MS_MOVE MS_REC MS_SILENT \
    MS_RELATIME MS_STRICTATIME MS_SLAVE MS_SHARED MS_PRIVATE \
    MS_UNBINDABLE MNT_DETACH MNT_FORCE

emit_section "prctl constants" \
    PR_SET_NO_NEW_PRIVS PR_CAPBSET_READ PR_CAPBSET_DROP PR_SET_KEEPCAPS \
    PR_CAP_AMBIENT PR_CAP_AMBIENT_RAISE PR_CAP_AMBIENT_LOWER \
    PR_CAP_AMBIENT_CLEAR_ALL PR_SET_CHILD_SUBREAPER PR_SET_PDEATHSIG \
    PR_SET_DUMPABLE PR_SET_NAME

# Capabilities (names extracted from C output, sorted by number)
printf '\n# %s\n# %s\n# %s\n' \
    "═══════════════════════════════════════════════════════════════════════" \
    "Capabilities" \
    "═══════════════════════════════════════════════════════════════════════"
echo 'our @CAP_NAMES = qw('
grep '^CAP_' "$TMPDIR/x86_64.txt" | sort -t= -k2 -n | cut -d= -f1 \
    | awk '{
        buf = buf " " $0
        if (NR % 5 == 0) { print "   " buf; buf = "" }
    }
    END { if (buf != "") print "   " buf }'
echo ');'
echo 'our %CAP_NUM;'
echo 'for my $i (0 .. $#CAP_NAMES) {$CAP_NUM{$CAP_NAMES[$i]} = $i;}'

printf '\nuse constant {\n'
printf '    _LINUX_CAPABILITY_VERSION_3 => %s,\n' "${CONST[_LINUX_CAPABILITY_VERSION_3]}"
printf '    _LINUX_CAPABILITY_U32S_3 => %s,\n' "${CONST[_LINUX_CAPABILITY_U32S_3]}"
printf '    VFS_CAP_REVISION_2 => %s,\n' "${CONST[VFS_CAP_REVISION_2]}"
printf '};\n'

emit_section "seccomp" \
    SECCOMP_SET_MODE_FILTER SECCOMP_FILTER_FLAG_TSYNC \
    SECCOMP_FILTER_FLAG_LOG SECCOMP_FILTER_FLAG_NEW_LISTENER \
    SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV

emit_section "BPF (cgroup device)" \
    BPF_PROG_LOAD BPF_PROG_ATTACH BPF_PROG_DETACH BPF_PROG_QUERY \
    BPF_CGROUP_DEVICE BPF_F_ALLOW_MULTI BPF_PROG_TYPE_CGROUP_DEVICE

printf '\n# %s\n# %s\n# %s\n' \
    "═══════════════════════════════════════════════════════════════════════" \
    "close_range" \
    "═══════════════════════════════════════════════════════════════════════"
printf 'use constant {CLOSE_RANGE_CLOEXEC => %s,};\n' "${CONST[CLOSE_RANGE_CLOEXEC]}"

emit_section "mount_setattr flags (kernel 5.12+)" \
    AT_RECURSIVE AT_EMPTY_PATH \
    MOUNT_ATTR_RDONLY MOUNT_ATTR_NOSUID MOUNT_ATTR_NODEV MOUNT_ATTR_NOEXEC \
    MOUNT_ATTR_NOATIME MOUNT_ATTR_STRICTATIME MOUNT_ATTR_NODIRATIME \
    MOUNT_ATTR__ATIME MOUNT_ATTR_NOSYMFOLLOW MOUNT_ATTR_IDMAP \
    OPEN_TREE_CLONE OPEN_TREE_CLOEXEC MOVE_MOUNT_F_EMPTY_PATH

emit_section "PTY / terminal ioctls" \
    TIOCGPTN TIOCSPTLCK TIOCSCTTY TIOCSWINSZ TIOCGWINSZ

cat <<'SIGNALS'

# ═══════════════════════════════════════════════════════════════════════
# Signals (name -> number, from Perl's Config at runtime)
# ═══════════════════════════════════════════════════════════════════════
use Config;
our %SIG_NUM;
{
    my @names = split ' ', $Config{sig_name};
    my @nums = split ' ', $Config{sig_num};
    for my $i (0 .. $#names) {
        $SIG_NUM{$names[$i]} = $nums[$i] if $names[$i] && $nums[$i];
    }
}
SIGNALS

# NS_MAP (Perl data, uses CLONE_* constants)
cat <<'NSMAP'

# ═══════════════════════════════════════════════════════════════════════
# OCI namespace type -> clone flag & proc name
# ═══════════════════════════════════════════════════════════════════════
our %NS_MAP = (
    pid => {flag => CLONE_NEWPID, proc => 'pid'},
    network => {flag => CLONE_NEWNET, proc => 'net'},
    mount => {flag => CLONE_NEWNS, proc => 'mnt'},
    ipc => {flag => CLONE_NEWIPC, proc => 'ipc'},
    uts => {flag => CLONE_NEWUTS, proc => 'uts'},
    user => {flag => CLONE_NEWUSER, proc => 'user'},
    cgroup => {flag => CLONE_NEWCGROUP, proc => 'cgroup'},
    time => {flag => CLONE_NEWTIME, proc => 'time_for_children'},
);
NSMAP

# Exports
cat <<'EXPORTS'

# ═══════════════════════════════════════════════════════════════════════
# Exports
# ═══════════════════════════════════════════════════════════════════════
our @EXPORT_OK = qw(
    O_CLOEXEC O_PATH

    SYS_mount SYS_umount2 SYS_pivot_root SYS_unshare SYS_setns
    SYS_clone SYS_clone3 SYS_prctl SYS_capget SYS_capset
    SYS_mknod SYS_mknodat SYS_seccomp SYS_bpf SYS_pidfd_open
    SYS_close_range SYS_sethostname SYS_setdomainname SYS_setgroups
    SYS_prlimit64 SYS_ioprio_set SYS_sched_setattr SYS_sched_setaffinity
    SYS_set_mempolicy SYS_keyctl SYS_add_key SYS_memfd_create
    SYS_open_tree SYS_move_mount SYS_mount_setattr
    SYS_fsopen SYS_fsconfig SYS_fsmount SYS_fchown
    SYS_sendmsg SYS_recvmsg SYS_epoll_create1 SYS_epoll_ctl
    SYS_epoll_wait SYS_inotify_init1 SYS_inotify_add_watch SYS_waitid

    CLONE_NEWNS CLONE_NEWUTS CLONE_NEWIPC CLONE_NEWUSER CLONE_NEWPID
    CLONE_NEWNET CLONE_NEWCGROUP CLONE_NEWTIME SIGCHLD

    MS_RDONLY MS_NOSUID MS_NODEV MS_NOEXEC MS_REMOUNT
    MS_NOATIME MS_NODIRATIME MS_BIND MS_MOVE MS_REC MS_SILENT
    MS_RELATIME MS_STRICTATIME MS_SLAVE MS_SHARED MS_PRIVATE
    MS_UNBINDABLE MNT_DETACH MNT_FORCE

    PR_SET_NO_NEW_PRIVS PR_CAPBSET_READ PR_CAPBSET_DROP PR_SET_KEEPCAPS
    PR_CAP_AMBIENT PR_CAP_AMBIENT_RAISE PR_CAP_AMBIENT_LOWER
    PR_CAP_AMBIENT_CLEAR_ALL PR_SET_CHILD_SUBREAPER PR_SET_PDEATHSIG
    PR_SET_DUMPABLE PR_SET_NAME

    @CAP_NAMES %CAP_NUM
    _LINUX_CAPABILITY_VERSION_3 _LINUX_CAPABILITY_U32S_3 VFS_CAP_REVISION_2

    SECCOMP_SET_MODE_FILTER SECCOMP_FILTER_FLAG_TSYNC
    SECCOMP_FILTER_FLAG_LOG SECCOMP_FILTER_FLAG_NEW_LISTENER
    SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV

    BPF_PROG_LOAD BPF_PROG_ATTACH BPF_PROG_DETACH BPF_PROG_QUERY
    BPF_CGROUP_DEVICE BPF_F_ALLOW_MULTI BPF_PROG_TYPE_CGROUP_DEVICE

    CLOSE_RANGE_CLOEXEC

    AT_RECURSIVE AT_EMPTY_PATH
    MOUNT_ATTR_RDONLY MOUNT_ATTR_NOSUID MOUNT_ATTR_NODEV MOUNT_ATTR_NOEXEC
    MOUNT_ATTR_NOATIME MOUNT_ATTR_STRICTATIME MOUNT_ATTR_NODIRATIME
    MOUNT_ATTR__ATIME MOUNT_ATTR_NOSYMFOLLOW MOUNT_ATTR_IDMAP
    OPEN_TREE_CLONE OPEN_TREE_CLOEXEC MOVE_MOUNT_F_EMPTY_PATH

    TIOCGPTN TIOCSPTLCK TIOCSCTTY TIOCSWINSZ TIOCGWINSZ

    %SIG_NUM %NS_MAP
);

1;
EXPORTS
}

# ── Run ─────────────────────────────────────────────────────────────
generated=$(gen)

if [ "$mode" = check ]; then
    if diff -u "$OUT" <(echo "$generated") >&2; then
        echo "OK: $OUT is up to date." >&2
    else
        echo "FAIL: $OUT is out of date. Run: scripts/gen_const.sh" >&2
        exit 1
    fi
else
    echo "$generated" > "$OUT"
    perl -c "$OUT" 2>&1
    echo "Generated $OUT" >&2
fi
